# Example without using docker image.
version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - python sagemaker-pipeline.py  # Runs the script directly